language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
 matrix:
  allow_failures:
  - julia: nightly
notifications:
  email: false
# script:
#   - julia -e 'Pkg.clone(pwd()); Pkg.build("Microeconometrics"); Pkg.test("Microeconometrics"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Microeconometrics")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'Pkg.add("Documenter")' ; 'cd(Pkg.dir("PACKAGE_NAME")); include(joinpath("docs", "make.jl"))'
